// Reusable in-test stand-in for the C++ `wallpaper` context object that
// production backend wrappers (Scene, Mpv, QtMultimedia, QtWebView) read
// from. We expose it as a sibling property; production code references
// `background.<name>` and QML JS scope chain resolves it via the parent
// component's id.
//
// Default values are wallpaper-engine "playable" state (not paused, audio
// on, scene displayMode). Tests can override after creation.
import QtQuick
QtObject {
    property int    displayMode: 0          // Common.DisplayMode.Aspect
    property string nowBackend:  ""
    property string userPropsJson: ""
    property real   volume:      50
    property bool   mute:        false
    property real   speed:       1.0
    property int    fps:         30
    property bool   mpvStats:    false
    property bool   hdrOutput:   false
    property bool   systemAudioCapture: false
    property bool   hasLib:      true
    property string source:      ""
    property string wallpaperPath: ""
    property string wallpaperType: ""
    property string workshopid:  ""
    property string steamlibrary: ""
    property string filterStr:   ""
    property bool   randomizeWallpaper: false
    property bool   noRandomWhilePaused: false
    property int    switchTimer: 1
    property bool   pauseOnBatPower: false
    property int    pauseBatPercent: 20
    property bool   mouseInput:  true
    property var    customConf:  ({ favor: new Set() })
    property string videoBackend: ""
    property bool   ok:          true
    property var    mouseHooker: null
    property bool   doHookMouse: false
    property bool   autoPause:   false
    // production code reads `background.Window`, but QML forbids capitalized
    // property names; tests that read `background.Window` will get undefined.
    property var    win:         null

    // Note: sourceChanged/mouseHookerChanged/okChanged/videoBackendChanged
    // are auto-generated by QML for the matching properties — declaring them
    // explicitly causes "Duplicate signal name" errors.
    signal sig_backendFirstFrame(string name)

    function get_opt_value(name) { return ""; }
    function hookMouse()         {}
    function hookMouseSlot()     {}
}
