// Test stub — see tests/qml/_stubs/README.md for contract.
// Real source: libtaskmanager (Plasma framework)
// Last contract review: 2026-05-27

import QtQuick
QtObject {
    // currentDesktopChanged is auto-generated by the property.
    property var currentDesktop: 0
}
