// Stub — Chromium isn't going to live in qmltestrunner. Production code
// (backend/QtWebView.qml) creates this and listens for loadingChanged etc.
// We provide just enough surface to instantiate and call methods.
import QtQuick
Item {
    property url url: ""
    property string html: ""
    property string title: ""
    // Real WebEngineView declares `loadingChanged(loadRequest)` as a custom
    // signal that doubles as the change signal for `loading`. Declaring
    // both `property bool loading` and the explicit signal collides under
    // QML's "duplicate signal" rule, so we drop the property and keep just
    // the explicit signal — production code reads `loadingInfo.status`,
    // never `web.loading` directly.
    signal loadingChanged(var loadRequest)
    property bool   audioMuted: false
    property var    settings: ({
        javascriptEnabled: true,
        localStorageEnabled: true,
    })
    property var    profile: ({})
    property var    webChannel: null

    // loadingChanged is auto-generated by the `loading` property.
    signal javaScriptConsoleMessage(int level, string message, int lineNumber, string sourceID)

    enum LoadStatus { LoadStartedStatus, LoadStoppedStatus, LoadSucceededStatus, LoadFailedStatus }
    enum LifecycleState { Active, Frozen, Discarded }

    function grabToImage(callback) {
        if (callback) callback({ url: "" });
    }

    property var userScripts: ({
        insert: function(scripts) {},
        clear:  function() {},
    })

    property int lifecycleState: WebEngineView.Active
    property bool activeFocusOnPress: true

    function loadHtml(html, baseUrl) {}
    function reload()                {}
    function stop()                  {}
    function runJavaScript(code, cb) { if (cb) cb(undefined); }
}
